# Be sure to restart your server when you modify this file.

# Add new inflection rules using the following format
# (all these examples are active by default):
ActiveSupport::Inflector.inflections do |inflect|
    #   inflect.plural /^(ox)$/i, '\1en'
    #  inflect.singular /^(ox)en/i, '\1'
       inflect.irregular 'controle', 'controles'
       inflect.irregular 'pesquisa', 'pesquisas'
       inflect.irregular 'estrutura', 'estruturas'
       inflect.irregular 'dpem', 'dpens'
       inflect.irregular 'arquiacao', 'arquiacoes'
       inflect.irregular 'estacao', 'estacoes'
       inflect.irregular 'titulo', 'titulos'
       inflect.irregular 'borda', 'bordas'
       inflect.irregular 'livre', 'livres'
       inflect.irregular 'inscricao', 'inscricoes'
       inflect.irregular 'tripulacao', 'tripulacoes'
       inflect.irregular 'material', 'materiais'
       inflect.irregular 'exintor', 'extintores'
       inflect.irregular 'abastecimento', 'abastecimentos'
       inflect.irregular 'quebra', 'quebras'
       inflect.irregular 'operacao', 'operacoes'
       inflect.irregular 'notificacao', 'notificacoes'
       inflect.irregular 'campo', 'campos'
       inflect.irregular 'situacao', 'situacoes'
       inflect.irregular 'filial', 'filiais'
       inflect.irregular 'analise', 'analises'
       inflect.irregular 'certificado', 'certificados'
       inflect.irregular 'critica', 'criticas'
       inflect.irregular 'fornecedor', 'fornecedores'
       inflect.irregular 'pedido', 'pedidos'
       inflect.irregular 'descricao', 'descricoes'
       inflect.irregular 'cadastro', 'cadastros'
       inflect.irregular 'linha', 'linhas'
       inflect.irregular 'navio', 'navios'
       inflect.irregular 'navegacao', 'navegacoes'
       inflect.irregular 'avaria', 'avarias'
       inflect.irregular 'viagem', 'viagens'
       inflect.irregular 'mensagem', 'mensagens'
       inflect.irregular 'posicao', 'posicoes'
       inflect.irregular 'responsavel', 'responsaveis'
       inflect.irregular 'solicitacao', 'solicitacoes'
       inflect.irregular 'comentario', 'comentarios'
       inflect.irregular 'cliente', 'clientes'
       inflect.irregular 'unidades', 'unidades'
       inflect.irregular 'oficina', 'oficinas'
       inflect.irregular 'programacao', 'programacoes'
       inflect.irregular 'carreta', 'carretas'
       inflect.irregular 'tecnico', 'tecnicos'
       inflect.irregular 'placa', 'placas'
       inflect.irregular 'rancho', 'ranchos'
       inflect.irregular 'ordem', 'ordens'
       inflect.irregular 'servico', 'servicos'
       inflect.irregular 'frota', 'frotas'
       inflect.irregular 'ocorrencia', 'ocorrencias'
       inflect.irregular 'tipo', 'tipos'
       inflect.irregular 'produto', 'produtos'
       inflect.irregular 'previsao', 'previsoes'
       inflect.irregular 'pneu', 'pneus'
       inflect.irregular 'combustivel', 'combustiveis'
       inflect.irregular 'relatorio', 'relatorios'
       inflect.irregular 'manutencao', 'manutencoes'
    #   inflect.uncountable %w( fish sheep )
     end
    #
    # These inflection rules are supported but not enabled by default:
    # ActiveSupport::Inflector.inflections do |inflect|
    #   inflect.acronym 'RESTful'
    # end
    